language: ruby
rvm:
  - 1.9.3
bundler_args: --without staging development deploy
before_install:
before_script: cp spec/dummy/config/database-sample.yml spec/dummy/config/database.yml; cd spec/dummy; bundle exec rake db:create;
script: rspec spec
branches:
  only:
    - master
notifications:
  hipchat: 5d580c1746812c946d9cb0b58f7a66@FMA
  email:
    - dev-fma@fiksu.com
